steering_predictor:
  ros__parameters:
      cmd_steering_topic: "cmd_servo"
      cmd_speed_topic: "cmd_throttle"
      image_topic: "realsense_camera/image_uncompressed"
      max_speed: 100
      min_speed: 80
      turn_right_steering_angle_rad: -1.0
      turn_left_steering_angle_rad: 1.0
      turn_right_cmd_steering: -1000
      turn_left_cmd_steering: 1000
      gain: 1.40

test_video_publisher:
    ros__parameters:
        video_filepath: "/home/parallels/dev_ws/src/lane_keeping_assist/share/test_videos/recorded_timestamp.mp4"
