core:
  ros__parameters:
    cmd_steering_topic: "cmd_servo"
    cmd_speed_topic: "cmd_throttle"
    max_speed: 100
    min_speed: 90
    turn_right_cmd_steering: -1000
    turn_left_cmd_steering: 1000
    gain: 1.50

steering_predictor:
  ros__parameters:
    image_topic: "realsense_camera/image_uncompressed"

lane_detector:
  ros__parameters:
    image_topic: "realsense_camera/image_uncompressed"

test_video_publisher:
  ros__parameters:
    video_filepath: "/home/parallels/dev_ws/src/lane_keeping_assist/share/test_videos/light_reflection.mp4"
