/**:
    ros__parameters:
      video_device: "/dev/video4"
      framerate: 60.0
      io_method: "mmap"
      frame_id: "camera"
      pixel_format: "yuyv2rgb"  # see usb_cam/supported_formats for list of supported formats
      av_device_format: "YUV422P"
      image_width: 424
      image_height: 240
      camera_name: "realsense"
      camera_info_url: "package://usb_cam/config/realsense_camera_info_.yaml"
      brightness: -1
      contrast: -1
      saturation: -1
      sharpness: -1
      gain: -1
      auto_white_balance: true
      white_balance: 4000
      autoexposure: true
      exposure: 100
      autofocus: false
      focus: -1
