#!/usr/bin/python3



# ***************************************************************************************************************************************************
#      |          This script was auto-generated by generate_Xicro_node.py which received parameters from setup_xicro.yaml                    |
#      |                                         EDITING THIS FILE BY HAND IS NOT RECOMMENDED                                                 |
# ***************************************************************************************************************************************************



# Generate xicro_node

from rclpy.action import ActionClient,ActionServer
import math
import rclpy
from rclpy.node import Node
from rclpy.executors import MultiThreadedExecutor
import numpy as np
import serial
# gen Import interfaces
# gen import msgfrom std_msgs.msg import Boolfrom ackermann_msgs.msg import AcKermanDrive# gen import srv client# gen import srv server# gen import action client# gen import action serverimport struct
import time
import multiprocessing as mp
import argparse
import sys






def checkNofdata(dataType):
    S=dataType.find("[")
    F= dataType.find("]")
    if(S!=-1 and F!=-1):
        return int(dataType[S+1:F])
    else:
        return 1
def typetoProtocol(typee,Nofdata):
    ans=0
    Nofbyte=0
    if(typee=="uint8"):
        ans=  8
        Nofbyte=1
    elif(typee=="uint16"):
        ans=  16
        Nofbyte=2
    elif(typee=="uint32"):
        ans=  32
        Nofbyte=4
    elif(typee=="uint64"):
        ans=  64
        Nofbyte=8
    elif(typee=="int8"):
        ans=  18
        Nofbyte=1
    elif(typee=="int16"):
        ans=  116
        Nofbyte=2
    elif(typee=="int32"):
        ans=  132
        Nofbyte=4
    elif(typee=="int64"):
        ans=  164
        Nofbyte=8
    elif(typee=="float32"):
        ans=  111
        Nofbyte=4
    elif(typee=="float64" ):
        ans= 222
        Nofbyte=8
    elif(typee=="string" ):
        ans= 242
        Nofbyte=888
    elif(typee=="bool" ):
        ans= 88
        Nofbyte=1
    elif(typee=="xxicro_Empty" ):
        ans= 254
        Nofbyte=1
    if(Nofdata==1):
        return ans,Nofbyte
    elif(typee=="bool" ):
        return ans+1,999
    else:
        return ans+1,Nofbyte

# gen setup


def setup_var_protocol():

